AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  implementtaggingandlcp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 600
      Handler: implement_tagging_and_lcp.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-southeast-2:920344503634:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-southeast-2:920344503634:log-group:/aws/lambda/implement-tagging-and-lcp:*
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:ListAllMyBuckets
                - s3:GetBucketTagging
                - s3:PutBucketTagging
                - s3:PutObject
                - s3:PutLifecycleConfiguration
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 ? 10-3 FRI *)
        Schedule2:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 ? 4-9 FRI *)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
