name: CD Deployment

on:
  workflow_run:
    workflows: ["CI Checks"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::537808241319:role/github-actions-implement-tagging-and-lcp
          aws-region: ap-southeast-2

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
