name: CI Checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::537808241319:role/github-actions-implement-tagging-and-lcp
          aws-region: ap-southeast-2

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Validate JSON files
        run: |
          for file in $(find src -name '*.json'); do
            echo "Validating json file $file"
            python -m json.tool $file
          done

      - name: Validate YAML files
        run: |
          echo "Validating yaml file"
          pip install yamllint
          yamllint --config-data "{extends: default, rules: {line-length: disable, document-start: disable}}" template.yaml

      - name: Validate SAM template
        run: |
          echo "Validating SAM template"
          sam validate --template-file template.yaml

      - name: Validate Cloudformation template
        run: |
          echo "Validating Cloudformation template"
          aws cloudformation validate-template

      - name: Lint Python files
        run: |
          echo "Linting Python files"
          pip install ruff
          ruff check src/*.py
