name: Deploy implement_tagging_and_lcp

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::537808241319:role/github-actions-implement-tagging-and-lcp
          aws-region: ap-southeast-2

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Validate JSON files
        run: |
          for file in $(find . -name '*.json'); do
            echo pwd
            echo "Validating $file"
            python -m json.tool $file
          done

      - name: Validate SAM template
        run: |
          echo "Validating template.yaml"
          sam validate --template-file template.yaml
